### ISSUE TITLE
Error after compilation on windows

### ISSUE THREAD

**Issue by DavidAce** [lukka/run-cmake#127]
I got the error below on my Windows CI, after the build step. Re-running the job did not help.

```
::remove-matcher owner=D%3A\a\_actions\lukka\run-cmake\v10\dist\all.json::
Error: "'D:\a\_temp\507572093\cmake-3.27.7-windows-x86_64\bin\cmake.exe' failed with error code: '1'.
    at CMakeRunner.<anonymous> (D:\a\_actions\lukka\run-cmake\v10\dist\index.js:6885:23)
    at Generator.next (<anonymous>)
    at fulfilled (D:\a\_actions\lukka\run-cmake\v10\dist\index.js:6700:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: run-cmake action execution failed: 'Error: "'D:\a\_temp\507572093\cmake-3.27.7-windows-x86_64\bin\cmake.exe' failed with error code: '1'.'
```
Is there anything I can do?
My workflow is [here](https://github.com/DavidAce/h5pp/actions/runs/6785554122/workflow?pr=20), the relevant part is:
```
- uses: lukka/get-cmake@latest
      [...]
      - name: Run CMakePreset
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'github-actions-${{ matrix.manager }}'
          configurePresetAdditionalArgs: "['-DH5PP_ENABLE_ASAN=FALSE']"
          buildPreset: 'github-actions-${{ matrix.manager }}'
          buildPresetAdditionalArgs: "['--config Debug']"
          testPreset: 'github-actions-${{ matrix.manager }}'
          testPresetAdditionalArgs: "['--build-config Debug']"
```

**Comment by DavidAce** [comment]
Thanks for pointing me in the right direction!
